# Generated by Django 5.1.1 on 2024-09-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_alter_moodentry_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodentry',
            old_name='feelings',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='moodentry',
            old_name='mood_intensity',
            new_name='jumlah_character',
        ),
        migrations.RenameField(
            model_name='moodentry',
            old_name='mood',
            new_name='nama_lengkap',
        ),
    ]
