# Generated by Django 5.1.1 on 2024-09-17 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_feelings_moodentry_deskripsi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodEntry',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
