# Generated by Django 5.1.1 on 2024-09-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
